language: node_js
node_js:
  - "node"

services:
  - docker

install:
  - yarn install -D

script:
  - mkdir ./dist/
  - yarn build
  - cp ./src/*.bs.js ./dist/
  - cp Dockerfile dist/
  - cd dist
  - node Scrapper.bs.js
  - docker build . -t journee-mondiale-api
